#!/usr/bin/env sh

ruby preprocess.rb the-elvish-language
cp style.css ../sindarin-release/
cp print.css ../sindarin-release/
cp -r fonts ../sindarin-release/

# print the PDF with Prince
~/Desktop/prince-10r7-macosx/lib/prince/bin/prince "../sindarin-release/the-elvish-language.html" -o elvish.pdf
